In [1]:
import clearwater_riverine as cwr
from pathlib import Path
import pandas as pd

In [2]:
# read config
working_dir = Path.cwd()
notebook_path = working_dir.parent.parent
network_path = notebook_path / 'examples/data_temp/sumwere_creek_coarse_p48'
config_file = network_path / 'example_config_refactor_no_chunk.yml'

In [3]:
# instantiate model
transport_model = cwr.ClearwaterRiverine(
    config_filepath=config_file,
)

In [4]:
# run model
transport_model.run()

In [5]:
# post-processing
mass_balance_model = transport_model.calculate_mass_balance(constituent_name='tracer')
mass_balance_answer = transport_model.calculate_mass_balance(
    constituent_name='tracer',
    calculate_answer=True,
    answer_value=100
)

In [6]:
mass_balance_model['global']

,volume_start,mass_start,volume_end_modeled,mass_end_modeled,volume_end_calculated,volume_error,volume_percent_error,mass_end_calculated,mass_error,mass_percent_error
0,36800.0,3680000.0,17900.029297,1790006.0,184030.923376,166130.894079,-4.27143,1.838748e+07,1.659748e+07,-4.268897

In [7]:
mass_balance_answer['global']

,volume_start,mass_start,volume_end_modeled,mass_end_modeled,volume_end_calculated,volume_error,volume_percent_error,mass_end_calculated,mass_error,mass_percent_error
0,36800.0,3680000.0,17900.029297,1790003.0,184030.923376,166130.894079,-4.27143,1.840309e+07,1.661309e+07,-4.27143

In [8]:
mass_balance_answer['boundary']

,volume_total,mass_total,volume_in,mass_in,volume_out,mass_out
boundary_name,,,,,,
CoriolisColdSpringCreek,-8.643002e+05,-8.643002e+07,-8.643002e+05,-8.643002e+07,0.000000e+00,0.000000e+00
DS_Stage,3.742120e+06,3.742120e+08,0.000000e+00,0.000000e+00,3.742120e+06,3.742120e+08
PwrPlnt_Flow,-4.321501e+05,-4.321501e+07,-4.321501e+05,-4.321501e+07,0.000000e+00,0.000000e+00
US_Flow,-2.592900e+06,-2.592900e+08,-2.592900e+06,-2.592900e+08,0.000000e+00,0.000000e+00
all_boundaries,-1.472309e+05,-1.472309e+07,-3.889351e+06,-3.889351e+08,3.742120e+06,3.742120e+08

In [ ]:
mass_balance_model['boundary']

,volume_total,mass_total,volume_in,mass_in,volume_out,mass_out
boundary_name,,,,,,
CoriolisColdSpringCreek,-8.643002e+05,-8.640002e+07,-8.643002e+05,-8.640002e+07,0.000000e+00,0.000000e+00
DS_Stage,3.742120e+06,3.740926e+08,0.000000e+00,0.000000e+00,3.742120e+06,3.740926e+08
PwrPlnt_Flow,-4.321501e+05,-4.320001e+07,-4.321501e+05,-4.320001e+07,0.000000e+00,0.000000e+00
US_Flow,-2.592900e+06,-2.592000e+08,-2.592900e+06,-2.592000e+08,0.000000e+00,0.000000e+00
all_boundaries,-1.472309e+05,-1.470748e+07,-3.889351e+06,-3.888001e+08,3.742120e+06,3.740926e+08

In [10]:
mass_balance_model['global']['mass_percent_error'] - mass_balance_answer['global']['mass_percent_error']

0    0.002533
Name: mass_percent_error, dtype: float64

In [11]:
mass_balance_model['global']['mass_percent_error'] - mass_balance_answer['global']['mass_percent_error']

0    0.002533
Name: mass_percent_error, dtype: float64

In [ ]:
from clearwater_riverine.variables import (
    BOUNDARY_FACE_INDEX,
    BOUNDARY_NAME
)

In [ ]:
boundary_index = transport_model.registry.get(BOUNDARY_FACE_INDEX)
boundary_names = transport_model.registry.get(BOUNDARY_NAME)

In [ ]:
boundary_name = 'US_Stage'

In [ ]:
boundary_names