# Run Riverine

## Imports

In [1]:
import clearwater_riverine as cwr
from pathlib import Path
import pandas as pd

## Paths

In [2]:
# read config
working_dir = Path.cwd()
notebook_path = working_dir.parent.parent
network_path = notebook_path / 'examples/data_temp/sumwere_creek_coarse_p48'
config_file = network_path / 'example_config_refactor_no_chunk.yml'

## Initialize and Run Model

In [3]:
# instantiate model
transport_model = cwr.ClearwaterRiverine(
    config_filepath=config_file,
)

In [4]:
# run model
transport_model.run()

## Post-Processing

Run for the tracer, then get the "answer" using 100 everywhere.

In [5]:
# post-processing: modeled results
mass_balance_model = transport_model.calculate_mass_balance(constituent_name='tracer')

# answer: 100 everywhere
mass_balance_answer = transport_model.calculate_mass_balance(
    constituent_name='tracer',
    calculate_answer=True,
    answer_value=100
)

Look at global results:

In [9]:
combined = pd.concat(
    [mass_balance_model['global'], mass_balance_answer['global']],
    keys=['mass_balance_model', 'mass_balance_answer']
)
combined

,,volume_start,mass_start,volume_end_modeled,mass_end_modeled,volume_end_calculated,volume_error,volume_percent_error,mass_end_calculated,mass_error,mass_percent_error
mass_balance_model,0,1295858.625,129585864.0,1442929.75,144292992.0,1.443090e+06,159.798376,-0.004109,1.442932e+08,237.937702,-0.000061
mass_balance_answer,0,1295858.625,129585864.0,1442929.75,144292992.0,1.443090e+06,159.798376,-0.004109,1.443090e+08,15964.337608,-0.004105

Look at boundary by boundary results:

In [ ]:
mass_balance_answer['boundary']

,volume_total,mass_total,volume_in,mass_in,volume_out,mass_out
boundary_name,,,,,,
CoriolisColdSpringCreek,-8.643002e+05,-8.643002e+07,-8.643002e+05,-8.643002e+07,0.000000e+00,0.000000e+00
DS_Stage,3.742120e+06,3.742120e+08,0.000000e+00,0.000000e+00,3.742120e+06,3.742120e+08
PwrPlnt_Flow,-4.321501e+05,-4.321501e+07,-4.321501e+05,-4.321501e+07,0.000000e+00,0.000000e+00
US_Flow,-2.592900e+06,-2.592900e+08,-2.592900e+06,-2.592900e+08,0.000000e+00,0.000000e+00
all_boundaries,-1.472309e+05,-1.472309e+07,-3.889351e+06,-3.889351e+08,3.742120e+06,3.742120e+08

In [ ]:
mass_balance_model['boundary']